version: '3.5'

services:

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: amor_quatro_patas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: GMT-0
    ports:
      - 5432:5432
    volumes:
      - .docker/data/postgres:/var/lib/postgresql/data
